openapi: 3.0.3
info:
  title: Course Task Tracker
  version: 1.0.0
  description: Create, retrieve, update, replace, and delete tasks. Also check server health.

servers:
  - url: http://localhost:3000

paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Server is running
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok
  /tasks:
    get:
      summary: List all tasks
      responses:
        "200":
          description: Tasks array retrieved
          content:
            application/json:
              schema:
                type: array
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
                required:
                  - tasks
              example:
                tasks:
                  - id: 1
                    title: Watch Week 3 lecture
                    course: CS453
                    completed: true
                  - id: 2
                    title: Complete midterm
                    course: CS553
                    completed: false
    post:
      summary: Create new task
      requestBody:
        required: true
        content:
          application/json:
            schema: # almost a Task, but without the id field.
              $ref: "#/components/schemas/TaskInput"
      responses:
        "201":
          description: Respond with new task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequest"
  
  /tasks/{id}:
    get:
      summary: Get task by ID
      responses:
        "200":
          description: Task retrieved
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    put:
      summary: Replace task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskInput" # The id is in the URI, not the request body
      responses:
        "200":
          description: Task replaced
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    patch:
      summary: Update task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/TaskUpdate"
      responses:
        "200":
          description: Task updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          $ref: "#/components/responses/BadRequest"
        "404":
          $ref: "#/components/responses/NotFound"
    delete:
      summary: Delete a task
      parameters:
        - name: id # parameter name is 'id'
          in: path # the id parameter is in the URI like '/tasks/{id}'
          # as opposed to '/tasks?id={id}'
          required: true
          schema:
            type: integer
      responses:
        "204":
          description: Task deleted
        "404":
          $ref: "#/components/responses/NotFound"

components:
  responses:
    BadRequest:
      description: Invalid JSON or bad request
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            error: Invalid JSON
    
    NotFound:
      description: Task not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/ErrorResponse"
          example:
            message: Task not found

  schemas:
    Task:
      type: object
      properties:
        id:
          type: integer
          example: 1
        title:
          type: string
          example: Watch Week 3 lecture
        course:
          type: string
          example: CS453
        completed:
          type: boolean
          example: false
      required:
        - id
        - title
        - course
        - completed

    TaskInput: # not sure how to create this without copy-pasting Task's schema
      type: object
      properties:
        title:
          type: string
          example: Watch Week 3 lecture
        course:
          type: string
          example: CS453
        completed:
          type: boolean
          example: false
      required:
        - title
        - course
        - completed

    TaskUpdate: # TaskInput but less strict; no required fields.
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        course:
          type: string
        completed:
          type: boolean
      # required: # only an id? --> No, because id is provided in URI rather than json body
      #   - id
    
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          example: Invalid input
      required:
        - error